name: unit-test

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'

jobs:
  golang-test:
    name: run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.15
        id: go

      - name: Test
        run: GO111MODULE=auto go test -cover ./...